# Generated by Django 3.1.7 on 2021-04-08 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lessonmanagement.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, verbose_name='Tên lớp')),
                ('startyear', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tên chính xác của môn học theo quy định của Bộ Giáo Dục', max_length=20, verbose_name='Tên môn học')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả môn học')),
                ('coverimage', models.ImageField(blank=True, null=True, upload_to='subject/', verbose_name='Ảnh bìa cho môn học')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tên chính xác của môn học theo quy định của Bộ Giáo Dục', max_length=20, verbose_name='Tên môn học')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả môn học')),
                ('coverimage', models.ImageField(blank=True, null=True, upload_to='subject/', verbose_name='Ảnh bìa cho môn học')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessonmanagement.groupsubject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, verbose_name='họ')),
                ('lastname', models.CharField(max_length=200, verbose_name='Tên')),
                ('zalo_number', models.DecimalField(decimal_places=0, help_text='Số điện thoại có đăng ký zalo, sử dụng để nhận thông báo từ ban giám hiệu', max_digits=12, verbose_name='Số điện thoại')),
                ('birth_date', models.DateField(verbose_name='Ngày sinh')),
                ('sex', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ')], max_length=6, verbose_name='Giới tính')),
                ('is_work', models.BooleanField(default=True, help_text='Tích vào ô nếu đang công tác tại trường, bỏ tích nếu đã nghỉ hưu hoặc chuyển sang đơn vị khác', verbose_name='Có đang công tác')),
                ('avatar', models.ImageField(blank=True, help_text='Ảnh nên được crop về ảnh vuông để đạt được độ thẩm mỹ cao nhất', null=True, upload_to=lessonmanagement.models.Teacher.user_directory_path, verbose_name='Ảnh đại diện')),
                ('main_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessonmanagement.subject', verbose_name='Chuyên môn')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Giáo viên',
                'verbose_name_plural': 'Danh sách giáo viên',
            },
        ),
        migrations.CreateModel(
            name='SubjectManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ghi chú')),
                ('role', models.CharField(blank=True, choices=[('member', 'Thành viên'), ('leader', 'Lãnh đạo')], max_length=10, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessonmanagement.teacher')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessonmanagement.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('lesson_path', models.FileField(upload_to='test/')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('start_number_lesson', models.IntegerField(blank=True, null=True)),
                ('end_number_lesson', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Chờ duyệt'), ('acept', 'Đã duyệt'), ('deny', 'Bị từ chối')], max_length=10)),
                ('note_checker', models.CharField(blank=True, max_length=200)),
                ('checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checker', to='lessonmanagement.teacher')),
                ('class_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessonmanagement.classyear')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessonmanagement.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='lessonmanagement.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='GroupSubjectManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ghi chú')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessonmanagement.groupsubject')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessonmanagement.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassYearManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ghi chú')),
                ('class_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessonmanagement.classyear')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessonmanagement.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
