# Generated by Django 3.2 on 2021-04-23 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lessonmanagement.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classyear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Tên lớp')),
                ('startyear', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Lớp học',
                'unique_together': {('title', 'startyear')},
            },
        ),
        migrations.CreateModel(
            name='GroupSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Tiêu đề')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Mô tả sơ lược')),
                ('cover', models.ImageField(upload_to='coverimages/', verbose_name='Ảnh bìa')),
            ],
            options={
                'verbose_name': 'Bộ môn',
                'verbose_name_plural': 'Bộ môn',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Tiêu đề')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Mô tả sơ lược')),
                ('cover', models.ImageField(upload_to='coverimages/', verbose_name='Ảnh bìa')),
            ],
            options={
                'verbose_name': 'Trường Học',
                'verbose_name_plural': 'Trường Học',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Tiêu đề')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Mô tả sơ lược')),
                ('cover', models.ImageField(upload_to='coverimages/', verbose_name='Ảnh bìa')),
                ('subject_slug', models.SlugField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject123', to='lessonmanagement.groupsubject')),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Môn học',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=20, verbose_name='Họ')),
                ('lastname', models.CharField(blank=True, max_length=20, verbose_name='Tên')),
                ('zalo_number', models.DecimalField(blank=True, decimal_places=0, help_text='Số điện thoại có đăng ký zalo, sử dụng để nhận thông báo từ ban giám hiệu', max_digits=12, null=True, verbose_name='Số điện thoại')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('sex', models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ')], max_length=6, null=True, verbose_name='Giới tính')),
                ('education_level', models.CharField(blank=True, choices=[('inter', 'Trung Cấp'), ('college', 'Cao Đẳng'), ('university', 'Đại Học'), ('master', 'Thạc Sĩ')], max_length=20, null=True)),
                ('is_work', models.BooleanField(default=True, help_text='Tích vào ô nếu đang công tác tại trường, bỏ tích nếu đã nghỉ hưu hoặc chuyển sang đơn vị khác', verbose_name='Có đang công tác')),
                ('avatar', models.ImageField(blank=True, help_text='Ảnh nên được crop về ảnh vuông để đạt được độ thẩm mỹ cao nhất', null=True, upload_to=lessonmanagement.models.Teacher.user_directory_path, verbose_name='Ảnh đại diện')),
                ('main_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessonmanagement.subject')),
                ('user', models.OneToOneField(blank=True, help_text='Tài khoản đăng nhập viết liền không dấu. Ví dụ: nhhieu. Viết tắt của Nguyễn Hữu Hiếu. Nếu trùng họ tên thì thêm số vào sau, ví dụ nhhieu2', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản đăng nhập')),
            ],
            options={
                'verbose_name': 'Giáo viên',
                'verbose_name_plural': 'Giáo viên',
            },
        ),
        migrations.CreateModel(
            name='SubjectTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Không: Nếu giáo viên đã nghỉ hưu hoặc thôi việc', verbose_name='Có hiệu lực không')),
                ('role', models.CharField(choices=[('member', 'Thành viên'), ('manager', 'Tổ trưởng')], max_length=10)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.teacher')),
            ],
            options={
                'verbose_name': 'Thành Viên/Quản lý Môn học',
                'verbose_name_plural': 'Thành Viên/Quản lý Môn học',
            },
        ),
        migrations.CreateModel(
            name='SubjectClassyear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lesson', models.IntegerField(blank=True, null=True, verbose_name='Tổng số tiết dạy')),
                ('is_teach_now', models.BooleanField(default=True, verbose_name='Trạng thái hiệu lực')),
                ('classyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.classyear')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.teacher')),
            ],
            options={
                'verbose_name': 'Phân công giảng dạy',
                'verbose_name_plural': 'Phân công giảng dạy',
            },
        ),
        migrations.CreateModel(
            name='SchoolManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Không: Nếu giáo viên đã nghỉ hưu hoặc thôi việc', verbose_name='Có hiệu lực không')),
                ('role', models.CharField(choices=[('submanager', 'Hiệu phó'), ('manager', 'Hiệu trưởng'), ('member', 'Khác')], max_length=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.teacher')),
            ],
            options={
                'verbose_name': 'Quản lý trường học ',
                'verbose_name_plural': 'Quản lý trường học',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('level', models.IntegerField(blank=True, choices=[(6, 6), (7, 7), (8, 8), (9, 9)], null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('start_number_lesson', models.IntegerField(blank=True, help_text='Bài giảng này ở tiết số mấy')),
                ('cout_number_lesson', models.IntegerField(blank=True, help_text='Bài giảng này trong bao nhiêu tiết')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Chờ duyệt'), ('acept', 'Đã duyệt'), ('deny', 'Bị từ chối')], default='pending', max_length=10)),
                ('check_date', models.DateTimeField(auto_now=True)),
                ('note_checker', models.CharField(blank=True, max_length=200)),
                ('checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_checker', to='lessonmanagement.teacher')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.teacher')),
            ],
            options={
                'verbose_name': 'Giáo Án',
                'verbose_name_plural': 'Giáo Án',
                'ordering': ['-upload_time'],
            },
        ),
        migrations.CreateModel(
            name='GroupSubjectManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Không: Nếu giáo viên đã nghỉ hưu hoặc thôi việc', verbose_name='Có hiệu lực không')),
                ('role', models.CharField(choices=[('submanager', 'Phó bộ môn'), ('manager', 'Trưởng bộ môn')], max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.groupsubject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.teacher')),
            ],
            options={
                'verbose_name': 'Quản lý Bộ môn',
                'verbose_name_plural': 'Quản lý Bộ môn',
            },
        ),
        migrations.CreateModel(
            name='ClassyearManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Không: Nếu giáo viên đã nghỉ hưu hoặc thôi việc', verbose_name='Có hiệu lực không')),
                ('classyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.classyear')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.teacher')),
            ],
            options={
                'verbose_name': 'Giáo viên chủ nhiệm',
                'verbose_name_plural': 'Giáo viên chủ nhiệm',
            },
        ),
        migrations.CreateModel(
            name='LessonClassyear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_teach', models.BooleanField(default=False)),
                ('teach_date', models.DateField(auto_now=True)),
                ('classyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.classyear')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.lesson')),
            ],
            options={
                'verbose_name': 'Giáo án thuộc lớp nào',
                'verbose_name_plural': 'Giáo án thuộc lớp nào',
                'unique_together': {('lesson', 'classyear')},
            },
        ),
    ]
