# Generated by Django 3.1.7 on 2021-04-07 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zalo_number', models.DecimalField(decimal_places=0, help_text='Số điện thoại có đăng ký zalo, sử dụng để nhận thông báo', max_digits=12, verbose_name='Số điện thoại')),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('Nam', 'Male'), ('Nữ', 'Female')], max_length=3)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
