# Generated by Django 3.2 on 2021-04-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsubject',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='coverimages/', verbose_name='Ảnh bìa'),
        ),
        migrations.AlterField(
            model_name='school',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='coverimages/', verbose_name='Ảnh bìa'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='coverimages/', verbose_name='Ảnh bìa'),
        ),
    ]
