# Generated by Django 3.2 on 2021-05-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='start_date_2',
            field=models.DateField(blank=True, help_text='Tuần 1 học kì 2 sẽ tính từ tuần này', null=True),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='start_date',
            field=models.DateField(help_text='Tuần 1 học kì 1 sẽ tính từ tuần này', unique_for_year='start_date'),
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
