# Generated by Django 3.2 on 2021-04-15 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectteacher',
            name='is_mainsubject',
        ),
    ]
