# Generated by Django 3.1.7 on 2021-04-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sex',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ')], max_length=6, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='zalo_number',
            field=models.DecimalField(decimal_places=0, help_text='Số điện thoại có đăng ký zalo, sử dụng để nhận thông báo từ ban giám hiệu', max_digits=12, verbose_name='Số điện thoại'),
        ),
    ]
