# Generated by Django 3.2 on 2021-05-15 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectlesson',
            options={'verbose_name': 'Chi tiết môn học ', 'verbose_name_plural': 'Chi tiết môn học '},
        ),
        migrations.AlterField(
            model_name='classyear',
            name='startyear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.schoolyear', verbose_name='Năm nhập học'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.groupsubject', verbose_name='Bộ môn'),
            preserve_default=False,
        ),
    ]
