# Generated by Django 3.1.7 on 2021-04-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Giáo viên', 'verbose_name_plural': 'Giáo viên'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='classyear',
            field=models.ManyToManyField(through='lessonmanagement.LessonClassYear', to='lessonmanagement.ClassYear'),
        ),
    ]
