# Generated by Django 3.2.7 on 2021-10-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonschedule',
            unique_together=set(),
        ),
    ]
