# Generated by Django 3.2 on 2021-05-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('subject', 'number_lesson', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonschedule',
            unique_together={('teach_date_schedule', 'session', 'order_schedule', 'lesson')},
        ),
    ]
