# Generated by Django 3.2 on 2021-05-09 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classyearmanager',
            name='enddate',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='classyearmanager',
            name='startdate',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='classyearmanager',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.teacher', verbose_name='Giáo viên'),
        ),
        migrations.AlterField(
            model_name='groupsubjectmanager',
            name='enddate',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='groupsubjectmanager',
            name='startdate',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='groupsubjectmanager',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.teacher', verbose_name='Giáo viên'),
        ),
        migrations.AlterField(
            model_name='schoolmanager',
            name='enddate',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='schoolmanager',
            name='role',
            field=models.CharField(choices=[('submanager', 'Hiệu phó'), ('manager', 'Hiệu trưởng'), ('member', 'Khác')], max_length=10, verbose_name='Vị trí'),
        ),
        migrations.AlterField(
            model_name='schoolmanager',
            name='startdate',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='schoolmanager',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.teacher', verbose_name='Giáo viên'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessonmanagement.groupsubject', verbose_name='Bộ môn'),
        ),
        migrations.AlterField(
            model_name='subjectteacher',
            name='enddate',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='subjectteacher',
            name='startdate',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='subjectteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.teacher', verbose_name='Giáo viên'),
        ),
    ]
