# Generated by Django 3.2 on 2021-06-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekschoolyear',
            name='semester',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='week',
            field=models.IntegerField(default=1, verbose_name='Tuần'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.DeleteModel(
            name='WeekSchoolyear',
        ),
    ]
