# Generated by Django 3.2.7 on 2021-09-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectclassyear',
            name='classyear',
            field=models.ManyToManyField(limit_choices_to={'startyear__start_date__year__in': [2022, 2021, 2020, 2019, 2018]}, to='lessonmanagement.Classyear'),
        ),
    ]
