# Generated by Django 3.2 on 2021-04-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonclassyear',
            name='subject_slug',
        ),
        migrations.AlterField(
            model_name='subjectclassyear',
            name='total_lesson',
            field=models.IntegerField(blank=True, default=1, verbose_name='Tổng số tiết dạy'),
            preserve_default=False,
        ),
    ]
