# Generated by Django 3.2 on 2021-04-15 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0002_remove_subjectteacher_is_mainsubject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Môn học', 'verbose_name_plural': 'Môn học'},
        ),
        migrations.AlterField(
            model_name='subjectteacher',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjectteacher', to='lessonmanagement.subject'),
        ),
    ]
