# Generated by Django 3.2 on 2021-04-23 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0002_auto_20210423_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject123', to='lessonmanagement.groupsubject', verbose_name='Bộ môn'),
        ),
    ]
