# Generated by Django 3.2 on 2021-04-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0002_auto_20210424_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='cout_number_lesson',
            field=models.IntegerField(help_text='Bài giảng này trong bao nhiêu tiết'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_number_lesson',
            field=models.IntegerField(help_text='Bài giảng này ở tiết số mấy'),
        ),
    ]
