# Generated by Django 3.1.7 on 2021-04-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0002_auto_20210412_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Định dạng: năm - tháng - ngày. Ví dụ: 1990-04-21', null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='zalo_number',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Số điện thoại có đăng ký zalo, sử dụng để nhận thông báo từ ban giám hiệu', max_digits=12, null=True, verbose_name='Số điện thoại'),
        ),
    ]
