# Generated by Django 3.2 on 2021-06-04 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0002_auto_20210523_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(choices=[(1, 1), (2, 2)])),
                ('schoolyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.schoolyear', verbose_name='Kì học')),
            ],
        ),
    ]
