# Generated by Django 3.2 on 2021-04-15 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0002_auto_20210415_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Giáo Án', 'verbose_name_plural': 'Giáo Án'},
        ),
    ]
