# Generated by Django 3.2 on 2021-05-15 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0002_auto_20210515_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectlevel',
            name='level',
        ),
        migrations.AlterField(
            model_name='subjectlevel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.subjectlesson', verbose_name='Môn học'),
        ),
    ]
