# Generated by Django 3.2 on 2021-06-07 09:30

from django.db import migrations, models
import django.db.models.deletion
import lessonmanagement.models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0002_auto_20210607_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classyearmanager',
            name='schoolyear',
            field=models.ForeignKey(default=lessonmanagement.models.q_schoolyear, on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.schoolyear'),
        ),
        migrations.AlterField(
            model_name='groupsubjectmanager',
            name='schoolyear',
            field=models.ForeignKey(default=lessonmanagement.models.q_schoolyear, on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.schoolyear'),
        ),
        migrations.AlterField(
            model_name='schoolmanager',
            name='schoolyear',
            field=models.ForeignKey(default=lessonmanagement.models.q_schoolyear, on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.schoolyear'),
        ),
        migrations.AlterField(
            model_name='subjectclassyear',
            name='schoolyear',
            field=models.ForeignKey(default=lessonmanagement.models.q_schoolyear, on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.schoolyear'),
        ),
        migrations.AlterField(
            model_name='subjectmanager',
            name='schoolyear',
            field=models.ForeignKey(default=lessonmanagement.models.q_schoolyear, on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.schoolyear'),
        ),
    ]
