# Generated by Django 3.2 on 2021-06-04 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0003_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='schoolyear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.schoolyear', verbose_name='năm học'),
        ),
        migrations.CreateModel(
            name='WeekSchoolyear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('start_date', models.DateField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.semester', verbose_name='kì học')),
            ],
        ),
    ]
