# Generated by Django 3.1.7 on 2021-04-07 02:48

from django.db import migrations, models
import lessonmanagement.models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0003_teacher_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Ảnh nên được crop về ảnh vuông để đạt được độ thẩm mỹ cao nhất', null=True, upload_to=lessonmanagement.models.Teacher.user_directory_path, verbose_name='Ảnh đại diện'),
        ),
    ]
