# Generated by Django 3.2 on 2021-04-15 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0003_auto_20210415_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupsubject',
            options={'verbose_name': 'Bộ môn', 'verbose_name_plural': 'Bộ môn'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject', to='lessonmanagement.groupsubject'),
        ),
    ]
