# Generated by Django 3.2 on 2021-06-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0003_auto_20210607_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='is_active',
            field=models.BooleanField(default=1, verbose_name='Năm học hiện tại'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subjectclassyear',
            name='classyear',
            field=models.ManyToManyField(limit_choices_to={'startyear__start_date__year__in': [2020, 2019, 2018, 2017]}, to='lessonmanagement.Classyear'),
        ),
    ]
