# Generated by Django 3.2 on 2021-04-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0003_auto_20210424_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectclassyear',
            name='total_lesson',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tổng số tiết dạy'),
        ),
    ]
