# Generated by Django 3.2 on 2021-05-12 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0003_auto_20210512_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(6, 6), (7, 7), (8, 8), (9, 9)])),
                ('number_lesson', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.subject')),
            ],
        ),
    ]
