# Generated by Django 3.1.7 on 2021-04-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0003_auto_20210414_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='check_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
