# Generated by Django 3.2 on 2021-04-15 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0003_alter_lesson_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectclassyear',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjectclassyearlist', to='lessonmanagement.teacher'),
        ),
    ]
