# Generated by Django 3.2 on 2021-05-09 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0003_auto_20210509_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectclassyear',
            name='min_lesson',
            field=models.IntegerField(default=1, verbose_name='Số tiết dạy 1 tuần'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subjectclassyear',
            name='schoolyear',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.schoolyear'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subjectclassyear',
            name='total_lesson',
            field=models.IntegerField(default=1, verbose_name='Tổng số tiết dạy'),
            preserve_default=False,
        ),
    ]
