# Generated by Django 3.2 on 2021-05-12 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0004_subjectlevel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('level', 'subject', 'number_lesson')},
        ),
    ]
