# Generated by Django 3.2 on 2021-04-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0004_auto_20210423_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classyear',
            name='class_level',
            field=models.IntegerField(blank=True),
        ),
    ]
