# Generated by Django 3.2 on 2021-05-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0004_auto_20210509_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectclassyear',
            name='classyear',
        ),
        migrations.AddField(
            model_name='subjectclassyear',
            name='classyear',
            field=models.ManyToManyField(to='lessonmanagement.Classyear'),
        ),
    ]
