# Generated by Django 3.2 on 2021-06-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0004_auto_20210608_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectdetail',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
