# Generated by Django 3.2 on 2021-04-26 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0004_alter_subjectclassyear_total_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectclassyear',
            options={'ordering': ('subject__title', '-classyear__startyear'), 'verbose_name': 'Phân công giảng dạy', 'verbose_name_plural': 'Phân công giảng dạy'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_teacher', to='lessonmanagement.teacher'),
        ),
    ]
