# Generated by Django 3.2 on 2021-06-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0004_lesson_schoolyear'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectclassyear',
            unique_together={('subject', 'teacher', 'schoolyear')},
        ),
    ]
