# Generated by Django 3.1.7 on 2021-04-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0004_auto_20210414_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='check_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
