# Generated by Django 3.2 on 2021-06-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0005_subjectdetail_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('subject', 'number_lesson', 'teacher', 'schoolyear')},
        ),
    ]
