# Generated by Django 3.2 on 2021-05-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0005_auto_20210509_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.IntegerField(choices=[(6, 6), (7, 7), (8, 8), (9, 9)], default=6, verbose_name='Khối'),
            preserve_default=False,
        ),
    ]
