# Generated by Django 3.1.7 on 2021-04-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0005_auto_20210414_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectclassyear',
            name='current_lesson',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjectclassyear',
            name='total_lesson',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
