# Generated by Django 3.1.7 on 2021-04-11 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0005_auto_20210411_0701'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='classyear',
            managers=[
            ],
        ),
    ]
