# Generated by Django 3.1.7 on 2021-04-07 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0005_auto_20210407_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tên chính xác của môn học theo quy định của Bộ Giáo Dục', max_length=20, verbose_name='Tên môn học')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả môn học')),
                ('coverimage', models.ImageField(blank=True, null=True, upload_to='subject/', verbose_name='Ảnh bìa cho môn học')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tên chính xác của môn học theo quy định của Bộ Giáo Dục', max_length=20, verbose_name='Tên môn học')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả môn học')),
                ('coverimage', models.ImageField(blank=True, null=True, upload_to='subject/', verbose_name='Ảnh bìa cho môn học')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessonmanagement.groupsubject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('note', models.CharField(max_length=200, verbose_name='Ghi chú')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessonmanagement.teacher')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessonmanagement.subject')),
            ],
        ),
    ]
