# Generated by Django 3.2 on 2021-04-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0005_alter_classyear_class_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classyear',
            name='class_level',
        ),
    ]
