# Generated by Django 3.2 on 2021-04-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0006_alter_lesson_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectclassyear',
            name='current_lesson',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
