# Generated by Django 3.2 on 2021-05-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0006_subject_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='total_lesson',
            field=models.IntegerField(default=1, verbose_name='Tổng số tiết'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='week_lesson',
            field=models.IntegerField(default=1, verbose_name='Số tiết mỗi tuần'),
            preserve_default=False,
        ),
    ]
