# Generated by Django 3.1.7 on 2021-04-07 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0006_groupsubject_subject_subjectmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSubjectManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('note', models.CharField(max_length=200, verbose_name='Ghi chú')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessonmanagement.groupsubject')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessonmanagement.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
