# Generated by Django 3.1.7 on 2021-04-14 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0006_auto_20210414_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectclassyear',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_subject_classyear', to='lessonmanagement.teacher'),
        ),
    ]
