# Generated by Django 3.2 on 2021-04-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0006_groupsubject_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-upload_time'], 'verbose_name': 'Giáo Án', 'verbose_name_plural': 'Giáo Án'},
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='classyear',
            new_name='classyear_list',
        ),
        migrations.AddField(
            model_name='classyear',
            name='lesson_list',
            field=models.ManyToManyField(through='lessonmanagement.LessonClassYear', to='lessonmanagement.Lesson'),
        ),
    ]
