# Generated by Django 3.2 on 2021-04-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0007_auto_20210418_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Chờ duyệt'), ('acept', 'Đã duyệt'), ('deny', 'Bị từ chối')], default='pending', max_length=10),
        ),
    ]
