# Generated by Django 3.1.7 on 2021-04-14 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0007_auto_20210414_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectclassyear',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessonmanagement.teacher'),
        ),
    ]
