# Generated by Django 3.2 on 2021-04-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0007_subjectclassyear_current_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectclassyear',
            name='edit_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
