# Generated by Django 3.1.7 on 2021-04-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0007_groupsubjectmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsubjectmanager',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupsubjectmanager',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjectmanager',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjectmanager',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
