# Generated by Django 3.2 on 2021-05-09 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0007_auto_20210509_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='level',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='total_lesson',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='week_lesson',
        ),
        migrations.CreateModel(
            name='SubjectLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(6, 6), (7, 7), (8, 8), (9, 9)], verbose_name='Khối')),
                ('total_lesson', models.IntegerField(verbose_name='Tổng số tiết')),
                ('week_lesson', models.IntegerField(verbose_name='Số tiết mỗi tuần')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.subject')),
            ],
        ),
    ]
