# Generated by Django 3.1.7 on 2021-04-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0008_auto_20210407_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsubjectmanager',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='subjectmanager',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ghi chú'),
        ),
    ]
