# Generated by Django 3.1.7 on 2021-04-14 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0008_auto_20210414_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectclassyear',
            options={'verbose_name': 'Giáo viên dạy môn và lớp', 'verbose_name_plural': 'Giáo viên dạy môn và lớp'},
        ),
    ]
