# Generated by Django 3.2 on 2021-04-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0008_subjectclassyear_edit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsubjectmanager',
            name='role',
            field=models.CharField(choices=[('member', 'Thành viên'), ('submanager', 'Phó bộ môn'), ('manager', 'Trưởng bộ môn')], max_length=10),
        ),
    ]
