# Generated by Django 3.2 on 2021-04-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0008_alter_lesson_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='end_number_lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='cout_number_lesson',
            field=models.IntegerField(blank=True, help_text='Bài giảng này trong bao nhiêu tiết', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_number_lesson',
            field=models.IntegerField(blank=True, help_text='Bài giảng này ở tiết số mấy', null=True),
        ),
    ]
