# Generated by Django 3.2 on 2021-04-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0009_auto_20210418_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='upload_time',
            field=models.DateTimeField(),
        ),
    ]
