# Generated by Django 3.2 on 2021-05-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0009_auto_20210509_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectclassyear',
            name='subjectlesson',
        ),
    ]
