# Generated by Django 3.2 on 2021-04-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0009_alter_groupsubjectmanager_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupsubjectmanager',
            options={'verbose_name': 'Thành Viên/Quản lý Bộ Môn', 'verbose_name_plural': 'Thành Viên/Quản lý Bộ Môn'},
        ),
        migrations.AddField(
            model_name='lessonclassyear',
            name='order_schedule',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='lessonclassyear',
            name='session',
            field=models.CharField(blank=True, choices=[('morning', 'Buổi sáng'), ('afternoon', 'Buổi chiều')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='lessonclassyear',
            name='teach_date_schedule',
            field=models.DateField(blank=True, null=True),
        ),
    ]
