# Generated by Django 3.1.7 on 2021-04-14 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0009_auto_20210414_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classyear',
            options={'verbose_name': 'Lớp học', 'verbose_name_plural': 'Lớp học'},
        ),
    ]
