# Generated by Django 3.1.7 on 2021-04-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0010_classyear_classyearmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classyear',
            name='startyear',
            field=models.IntegerField(),
        ),
    ]
