# Generated by Django 3.1.7 on 2021-04-14 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0010_auto_20210414_1050'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classyear',
            unique_together={('title', 'startyear')},
        ),
    ]
