# Generated by Django 3.2 on 2021-04-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0010_auto_20210428_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='classyear',
            field=models.ManyToManyField(through='lessonmanagement.LessonClassyear', to='lessonmanagement.Classyear'),
        ),
    ]
