# Generated by Django 3.2 on 2021-04-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0011_lesson_classyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
