# Generated by Django 3.2 on 2021-04-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0012_alter_lesson_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='upload_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
