# Generated by Django 3.2 on 2021-05-03 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0013_alter_lesson_upload_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('cover', models.FileField(blank=True, null=True, upload_to='news/', verbose_name='File đính kèm trong tin tức')),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.teacher')),
            ],
        ),
    ]
