# Generated by Django 3.2 on 2021-05-03 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0014_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='teacher',
            new_name='creater',
        ),
        migrations.CreateModel(
            name='NewsTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_view', models.DateTimeField(auto_now=True)),
                ('is_view', models.BooleanField(default=False)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.news')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.teacher')),
            ],
        ),
    ]
