# Generated by Django 3.2 on 2021-05-03 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0015_auto_20210503_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-upload_time']},
        ),
        migrations.AddField(
            model_name='news',
            name='viewer',
            field=models.ManyToManyField(to='lessonmanagement.Teacher'),
        ),
        migrations.AlterField(
            model_name='news',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_news', to='lessonmanagement.teacher'),
        ),
        migrations.DeleteModel(
            name='NewsTeacher',
        ),
    ]
