# Generated by Django 3.2 on 2021-04-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0015_alter_lesson_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsubject',
            name='slug',
            field=models.SlugField(blank=True, default='djangodbmodelsfieldscharfield', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, default='djangodbmodelsfieldscharfield', max_length=100, null=True),
        ),
    ]
