# Generated by Django 3.2 on 2021-05-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0016_auto_20210503_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='viewer',
            field=models.ManyToManyField(blank=True, null=True, to='lessonmanagement.Teacher'),
        ),
    ]
