# Generated by Django 3.2 on 2021-04-20 16:01

from django.db import migrations, models
import lessonmanagement.models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0016_auto_20210420_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsubject',
            name='slug',
            field=models.SlugField(blank=True, default=lessonmanagement.models.SubjectAbstract.get_slug, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, default=lessonmanagement.models.SubjectAbstract.get_slug, max_length=100, null=True),
        ),
    ]
