# Generated by Django 3.2 on 2021-05-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0017_alter_news_viewer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['upload_time']},
        ),
    ]
