# Generated by Django 3.2 on 2021-04-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0018_auto_20210420_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsubject',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='slug',
        ),
        migrations.AddField(
            model_name='teacher',
            name='education_level',
            field=models.CharField(blank=True, choices=[('inter', 'Trung Cấp'), ('college', 'Đại Học'), ('university', 'Đại Học'), ('master', 'Thạc Sĩ')], max_length=20, null=True),
        ),
    ]
