# Generated by Django 3.2 on 2021-04-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0019_auto_20210421_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsubjectmanager',
            name='role',
            field=models.CharField(blank=True, choices=[('member', 'Phó bộ môn'), ('manager', 'Trưởng bộ môn')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subjectteacher',
            name='role',
            field=models.CharField(blank=True, choices=[('member', 'Thành viên'), ('manager', 'Tổ trưởng')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='education_level',
            field=models.CharField(blank=True, choices=[('inter', 'Trung Cấp'), ('college', 'Cao Đẳng'), ('university', 'Đại Học'), ('master', 'Thạc Sĩ')], max_length=20, null=True),
        ),
    ]
