# Generated by Django 3.2 on 2021-05-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0019_alter_lesson_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_path',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
