# Generated by Django 3.2 on 2021-05-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0020_lesson_lesson_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='upload_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
