# Generated by Django 3.2 on 2021-05-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0021_alter_lesson_upload_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonclassyear',
            options={'verbose_name': 'Lịch báo giảng', 'verbose_name_plural': 'Lịch báo giảng'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='edit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
