# Generated by Django 3.2 on 2021-04-21 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0021_auto_20210421_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsubjectmanager',
            name='role',
        ),
    ]
