# Generated by Django 3.2 on 2021-05-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0022_auto_20210504_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonclassyear',
            name='teach_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
