# Generated by Django 3.2 on 2021-04-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0022_remove_groupsubjectmanager_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsubjectmanager',
            name='role',
            field=models.CharField(blank=True, choices=[('member', 'Phó bộ môn'), ('manager', 'Trưởng bộ môn')], max_length=10, null=True),
        ),
    ]
