# Generated by Django 3.2 on 2021-05-04 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0023_alter_lessonclassyear_teach_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonclassyear',
            unique_together=set(),
        ),
    ]
