# Generated by Django 3.2 on 2021-04-21 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0023_groupsubjectmanager_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ghi chú')),
                ('role', models.CharField(blank=True, choices=[('member', 'Hiệu phó'), ('manager', 'Hiệu trưởng')], max_length=10, null=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessonmanagement.teacher')),
            ],
            options={
                'verbose_name': 'Quản lý trường ',
                'verbose_name_plural': 'Quản lý trường',
            },
        ),
    ]
