# Generated by Django 3.2 on 2021-05-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0024_alter_lessonclassyear_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schoolyear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('spring_start', models.DateField(blank=True, help_text='Giờ mùa hè. Áp dụng từ ngày nào', null=True)),
                ('sprint_duration', models.DurationField()),
            ],
        ),
    ]
