# Generated by Django 3.2 on 2021-05-05 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0025_schoolyear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolyear',
            old_name='sprint_duration',
            new_name='spring_duration',
        ),
    ]
