# Generated by Django 3.2 on 2021-04-21 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0027_alter_lesson_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='slug',
            new_name='slug_subject',
        ),
    ]
