# Generated by Django 3.2 on 2021-05-05 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0027_auto_20210505_0742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolyear',
            options={'verbose_name': 'Năm học', 'verbose_name_plural': 'Năm học'},
        ),
        migrations.RenameField(
            model_name='schoolyear',
            old_name='spring_morning_start',
            new_name='spring_start',
        ),
        migrations.RenameField(
            model_name='schoolyear',
            old_name='winter_morning_start',
            new_name='winter_start',
        ),
        migrations.RemoveField(
            model_name='schoolyear',
            name='spring_afternoon_end',
        ),
        migrations.RemoveField(
            model_name='schoolyear',
            name='spring_afternoon_start',
        ),
        migrations.RemoveField(
            model_name='schoolyear',
            name='spring_morning_end',
        ),
        migrations.RemoveField(
            model_name='schoolyear',
            name='winter_afternoon_end',
        ),
        migrations.RemoveField(
            model_name='schoolyear',
            name='winter_afternoon_start',
        ),
        migrations.RemoveField(
            model_name='schoolyear',
            name='winter_morning_end',
        ),
        migrations.AddField(
            model_name='lesson',
            name='schoolyear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.schoolyear'),
        ),
        migrations.AddField(
            model_name='subjectclassyear',
            name='schoolyear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessonmanagement.schoolyear'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='start_date',
            field=models.DateField(help_text='Ngày bắt đầu năm học'),
        ),
    ]
