# Generated by Django 3.2 on 2021-04-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0028_rename_slug_lesson_slug_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonclassyear',
            name='teach_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
