# Generated by Django 3.2 on 2021-05-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0029_alter_schoolyear_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='start_date',
            field=models.DateField(help_text='Ngày bắt đầu năm học', unique_for_year='start_date'),
        ),
    ]
