# Generated by Django 3.2 on 2021-04-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0029_alter_lessonclassyear_teach_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonclassyear',
            unique_together={('lesson', 'classyear')},
        ),
    ]
