# Generated by Django 3.2 on 2021-04-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0030_alter_lessonclassyear_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectclassyear',
            name='is_teach_now',
            field=models.BooleanField(blank=True, null=True, verbose_name='Trạng thái hiệu lực'),
        ),
    ]
