# Generated by Django 3.2 on 2021-04-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0031_subjectclassyear_is_teach_now'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectclassyear',
            options={'verbose_name': 'Phân công giảng dạy', 'verbose_name_plural': 'Phân công giảng dạy'},
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
