# Generated by Django 3.2 on 2021-05-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0032_alter_lessonclassyear_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_path',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
