# Generated by Django 3.2 on 2021-04-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0033_auto_20210422_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='classyear',
            name='class_level_field',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
