# Generated by Django 3.2 on 2021-05-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0033_alter_lesson_lesson_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_path',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
