# Generated by Django 3.2 on 2021-04-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0034_classyear_class_level_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classyear',
            name='class_level_field',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
