# Generated by Django 3.2 on 2021-04-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmanagement', '0035_alter_classyear_class_level_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsubject',
            name='title',
            field=models.CharField(help_text='Tên chính xác của môn học theo quy định của Bộ Giáo Dục', max_length=20, unique=True, verbose_name='Tên môn học'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(help_text='Tên chính xác của môn học theo quy định của Bộ Giáo Dục', max_length=20, unique=True, verbose_name='Tên môn học'),
        ),
    ]
